packages:
  - 'packages/*'

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': '^9.0.0'
    '@typescript-eslint/eslint-plugin>eslint': '^9.0.0'
    '@typescript-eslint/parser>eslint': '^9.0.0'
    '@typescript-eslint/type-utils>eslint': '^9.0.0'
    '@typescript-eslint/utils>eslint': '^9.0.0'
    'eslint-plugin-import>eslint': '^9.0.0'
    'eslint-plugin-jsdoc>eslint': '^9.0.0'
    'eslint-plugin-prettier>eslint': '^9.0.0'
    'eslint-plugin-react>eslint': '^9.0.0'
    'eslint-plugin-react-hooks>eslint': '^9.0.0'
